#
# Stolen from AbnormalPoof's fork, didnt knew workflows existed lmao
#

# This is a basic workflow to help you get started with Actions


name: COMPILE ON LINUX

# Controls when the workflow will run
on:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
     
      - uses: actions/checkout@main
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.4
      # Runs a set of commands using the runners shell
      - name: funny dependencies
        run: |
          mkdir "%HAXELIB_ROOT%"
          haxelib setup "%HAXELIB_ROOT%"
          haxelib install lime 7.9.0
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install hscript
          haxelib install akifox-asynchttp
          haxelib install flixel-addons
          haxelib install newgrounds
          haxelib install linc_luajit
          haxelib install akifox-asynchttp
          haxelib install hxp
          haxelib git faxe https://github.com/uhrobots/faxe
          haxelib install polymod 
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git hscript-yoshiengine https://github.com/YoshiCrafter29/hscript-improved
      
      - name: configure android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          haxelib run lime config ANDROID_SETUP true
      - name: build
        run: haxelib run lime build android
      - uses: actions/upload-artifact@main
        with:
          name: Yoshi Engine (Android)
          path: export/release/android/bin
